name: Node CI

on:
  push:
    branches:
      - main


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Server Test
        run: node index.js